packages:
  # 应用目录
  - 'apps/*'
  # 文档目录
  - 'docs/*'
  # 包目录
  - 'packages/*'
  # 共享配置目录
  - 'tooling/*'

allowBuilds:
  electron-winstaller: true
  esbuild: true

catalogs:
  # 开发目录
  dev:
    '@types/node': ^26.1.1
    turbo: ^2.10.7
    typescript: 6.0.3
  # 前端依赖
  frontend:
    electron: ^43.2.0
    electron-builder: ^26.15.3
    electron-vite: ^5.0.0
    nuxt: ^4.5.1
    vue: ^3.5.40
    vue-router: ^5.2.0
