#!/usr/bin/env node
/**
 * Materialize the platform-neutral truth layer (.agents/**, .mcp.json) into
 * per-harness view directories (.trae/**, .claude/**).
 *
 * Views are generated artifacts — never edit them by hand; edit the truth
 * source and re-run `pnpm sync:harness`. Copied 1:1; stale view files are
 * pruned; pre-existing symlinks in view positions are removed first (writing
 * through a symlink would corrupt the truth layer on core.symlinks=false hosts).
 *
 * Usage:
 *   node scripts/sync-harness.cjs                 # copy truth → views (prune stale)
 *   node scripts/sync-harness.cjs --check         # list drift to stderr, exit 1, write nothing
 *   node scripts/sync-harness.cjs --strip-mcp-type  # also strip "type" from .trae/mcp.json copy
 */
const fs = require('node:fs')
const path = require('node:path')

const ROOT = path.resolve(__dirname, '..')
const CHECK = process.argv.includes('--check')
const STRIP_DEFAULT = false // flip to true if Trae rejects the typed .mcp.json schema
const STRIP_MCP_TYPE = process.argv.includes('--strip-mcp-type') || STRIP_DEFAULT
const VIEW_MARKER = '.sync-generated'

// [truthDir, viewDir] — every file under truth is copied to the same relative
// path under each view. FILE_VIEWS are single-file copies.
const DIR_VIEWS = [
  ['.agents/rules', '.trae/rules'],
  ['.agents/rules', '.claude/rules'],
  ['.agents/agents', '.trae/agents'],
  ['.agents/agents', '.claude/agents'],
  ['.agents/skills', '.trae/skills'],
  ['.agents/skills', '.claude/skills'],
]
const FILE_VIEWS = [['.mcp.json', '.trae/mcp.json']]

// Per-view frontmatter dialects: the truth layer carries the Trae superset
// (alwaysApply + description + globs + paths); each platform's view keeps only
// the fields its own schema supports (VS Code's Claude extension rejects
// Trae-only fields, so .claude/rules copies must be trimmed, not verbatim).
const VIEW_FM_DROPS = new Map([
  ['.trae/rules', ['paths']],
  ['.claude/rules', ['alwaysApply', 'globs', 'scene']],
])

function trimFrontmatter(text, dropKeys) {
  const m = text.match(/^(---\r?\n)([\s\S]*?)(\r?\n---)/)
  if (!m) return text
  const lines = m[2].split(/\r?\n/)
  const out = []
  let skipping = false
  for (const line of lines) {
    const top = /^([A-Za-z_-]+):/.exec(line)
    if (top) skipping = dropKeys.includes(top[1])
    if (!skipping) out.push(line)
  }
  return m[1] + out.join('\n') + m[3] + text.slice(m[0].length)
}

function viewDropKeys(viewRel) {
  for (const [dir, drop] of VIEW_FM_DROPS) {
    if (viewRel === dir || viewRel.startsWith(dir + '/')) return drop
  }
  return null
}

function relOf(abs) {
  return path.relative(ROOT, abs).replace(/\\/g, '/')
}

function walkFiles(abs) {
  const out = []
  if (!fs.existsSync(abs)) return out
  for (const entry of fs.readdirSync(abs, { withFileTypes: true })) {
    const child = path.join(abs, entry.name)
    if (entry.isDirectory()) out.push(...walkFiles(child))
    else out.push(child)
  }
  return out
}

function stripMcpType(text) {
  const json = JSON.parse(text)
  for (const server of Object.values(json.mcpServers ?? {})) delete server.type
  return JSON.stringify(json, null, 2) + '\n'
}

function expectedViewContent(truthAbs, viewRel) {
  let text = fs.readFileSync(truthAbs, 'utf8')
  if (viewRel === '.trae/mcp.json' && STRIP_MCP_TYPE) return stripMcpType(text)
  const drop = viewDropKeys(viewRel)
  if (drop) return trimFrontmatter(text, drop)
  return text
}

const drift = []

function collectJobs() {
  const jobs = [] // { truthAbs, viewAbs }
  for (const [truthDir, viewDir] of DIR_VIEWS) {
    const truthAbs = path.join(ROOT, truthDir)
    if (!fs.existsSync(truthAbs)) {
      drift.push(`truth layer incomplete: ${truthDir} missing`)
      continue
    }
    for (const file of walkFiles(truthAbs)) {
      jobs.push({
        truthAbs: file,
        viewAbs: path.join(ROOT, viewDir, path.relative(truthAbs, file)),
      })
    }
  }
  for (const [truthRel, viewRel] of FILE_VIEWS) {
    const truthAbs = path.join(ROOT, truthRel)
    if (!fs.existsSync(truthAbs)) {
      drift.push(`truth layer incomplete: ${truthRel} missing`)
      continue
    }
    jobs.push({ truthAbs, viewAbs: path.join(ROOT, viewRel) })
  }
  return jobs
}

function collectStale(jobs) {
  const produced = new Set(jobs.map((j) => relOf(j.viewAbs)))
  const stale = []
  for (const [truthDir, viewDir] of DIR_VIEWS) {
    // Truth side not migrated yet → its view is not generated by us; never prune.
    if (!fs.existsSync(path.join(ROOT, truthDir))) continue
    for (const abs of walkFiles(path.join(ROOT, viewDir))) {
      const rel = relOf(abs)
      if (path.basename(rel) === VIEW_MARKER) continue
      if (!produced.has(rel)) stale.push(abs)
    }
  }
  for (const [truthRel, viewRel] of FILE_VIEWS) {
    if (!fs.existsSync(path.join(ROOT, truthRel))) continue
    const abs = path.join(ROOT, viewRel)
    if (fs.existsSync(abs) && !produced.has(relOf(abs))) stale.push(abs)
  }
  return stale
}

function lstatSafe(p) {
  try {
    return fs.lstatSync(p)
  } catch {
    return null
  }
}

function removeExisting(viewAbs) {
  const st = lstatSafe(viewAbs)
  if (!st) return
  if (st.isSymbolicLink() || st.isFile()) fs.rmSync(viewAbs)
  else fs.rmSync(viewAbs, { recursive: true })
}

function main() {
  const jobs = collectJobs()
  const stale = collectStale(jobs)

  if (CHECK) {
    for (const job of jobs) {
      const st = lstatSafe(job.viewAbs)
      if (!st) {
        drift.push(`missing view: ${relOf(job.viewAbs)}`)
        continue
      }
      if (st.isSymbolicLink()) drift.push(`view is a symlink: ${relOf(job.viewAbs)}`)
      else if (
        fs.readFileSync(job.viewAbs, 'utf8') !==
        expectedViewContent(job.truthAbs, relOf(job.viewAbs))
      )
        drift.push(`drifted view: ${relOf(job.viewAbs)}`)
    }
    for (const abs of stale) drift.push(`stale view file: ${relOf(abs)}`)
    for (const viewDir of [
      ...DIR_VIEWS.map(([, v]) => v),
      ...FILE_VIEWS.map(([, v]) => path.dirname(v)),
    ]) {
      if (!fs.existsSync(path.join(ROOT, viewDir, VIEW_MARKER)))
        drift.push(`missing marker: ${viewDir}/${VIEW_MARKER}`)
    }
    if (drift.length > 0) {
      for (const d of drift) process.stderr.write(`[sync-harness] ${d}\n`)
      process.stderr.write('[sync-harness] run `pnpm sync:harness` to materialize views\n')
      process.exit(1)
    }
    console.log('[sync-harness] views in sync')
    return
  }

  for (const abs of stale) removeExisting(abs)
  for (const job of jobs) {
    const st = lstatSafe(job.viewAbs)
    if (st?.isSymbolicLink()) fs.rmSync(job.viewAbs) // never write through a symlink
    fs.mkdirSync(path.dirname(job.viewAbs), { recursive: true })
    fs.writeFileSync(job.viewAbs, expectedViewContent(job.truthAbs, relOf(job.viewAbs)))
  }
  for (const viewDir of [
    ...DIR_VIEWS.map(([, v]) => v),
    ...FILE_VIEWS.map(([, v]) => path.dirname(v)),
  ]) {
    const marker = path.join(ROOT, viewDir, VIEW_MARKER)
    if (!fs.existsSync(marker)) {
      fs.mkdirSync(viewDir, { recursive: true })
      fs.writeFileSync(
        marker,
        'generated by scripts/sync-harness.cjs — edit the .agents truth layer instead\n',
      )
    }
  }
  console.log(`[sync-harness] synced ${jobs.length} files, pruned ${stale.length}`)
}

main()
